name: Publish extension

on:
  push:
    branches:
    - main
  release:
    types:
    - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install

    - name: Publish with vsce
      if: startsWith( github.ref, 'refs/tags/')
      run: npx vsce publish --pat ${{ secrets.VSCE_PAT }}